export const RARITIES = ['common', 'uncommon', 'rare', 'legendary', 'secret'];

// Each plant defines: stem, leaves, bloom. All optional — set to null to skip.
// Colors are hex strings. Builder in svg.js renders these to a 100x120 viewBox.
export const PLANTS = [
  // ── COMMON ─────────────────────────────────────────────────────────────
  { id: 'grass',     name: 'Grass',     rarity: 'common',
    stem: null,
    leaves: { color: '#4ea84a', style: 'blade', count: 9 },
    bloom: null },
  { id: 'clover',    name: 'Clover',    rarity: 'common',
    stem: { color: '#3a8b3a', height: 30 },
    leaves: { color: '#5cb85c', style: 'trefoil', count: 1 },
    bloom: null },
  { id: 'dandelion', name: 'Dandelion', rarity: 'common',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#6cb05c', style: 'jagged', count: 4 },
    bloom: { color: '#ffd24a', centerColor: '#ffb022', kind: 'puff', size: 14, petals: 0 } },
  { id: 'moss',      name: 'Moss',      rarity: 'common',
    stem: null,
    leaves: { color: '#3a7a3a', style: 'clump', count: 7 },
    bloom: null },
  { id: 'fern',      name: 'Fern',      rarity: 'common',
    stem: { color: '#3a6a2a', height: 50 },
    leaves: { color: '#4a8a3a', style: 'frond', count: 5 },
    bloom: null },
  { id: 'daisy',     name: 'Daisy',     rarity: 'common',
    stem: { color: '#4a7a3a', height: 60 },
    leaves: { color: '#5ca84a', style: 'oval', count: 2 },
    bloom: { color: '#f4f0e6', centerColor: '#f0c040', kind: 'petals', size: 18, petals: 10 } },
  { id: 'buttercup', name: 'Buttercup', rarity: 'common',
    stem: { color: '#4a8a3a', height: 50 },
    leaves: { color: '#5cb85c', style: 'jagged', count: 3 },
    bloom: { color: '#ffd84a', centerColor: '#d49020', kind: 'petals', size: 14, petals: 5 } },
  { id: 'mint',      name: 'Mint',      rarity: 'common',
    stem: { color: '#5a8a4a', height: 60 },
    leaves: { color: '#6cc06c', style: 'serrated', count: 6 },
    bloom: { color: '#f0f0e0', centerColor: '#c0c0a0', kind: 'cluster', size: 10, petals: 5 } },
  { id: 'basil',     name: 'Basil',     rarity: 'common',
    stem: { color: '#3a6a2a', height: 50 },
    leaves: { color: '#3a8a3a', style: 'oval', count: 6 },
    bloom: null },
  { id: 'parsley',   name: 'Parsley',   rarity: 'common',
    stem: { color: '#3a7a2a', height: 35 },
    leaves: { color: '#4a9a3a', style: 'curly', count: 6 },
    bloom: null },
  { id: 'chives',    name: 'Chives',    rarity: 'common',
    stem: null,
    leaves: { color: '#5a9a5a', style: 'blade', count: 7 },
    bloom: { color: '#b86fd8', centerColor: '#8a4ab0', kind: 'puff', size: 10, petals: 0 } },
  { id: 'ivy',       name: 'Ivy',       rarity: 'common',
    stem: { color: '#3a5a2a', height: 70 },
    leaves: { color: '#3a7a3a', style: 'heart', count: 5 },
    bloom: null },

  // ── UNCOMMON ───────────────────────────────────────────────────────────
  { id: 'sunflower', name: 'Sunflower', rarity: 'uncommon',
    stem: { color: '#4a7a2a', height: 65 },
    leaves: { color: '#5a9a3a', style: 'heart', count: 2 },
    bloom: { color: '#ffd224', centerColor: '#6a3a18', kind: 'petals', size: 26, petals: 14 } },
  { id: 'rose',      name: 'Rose',      rarity: 'uncommon',
    stem: { color: '#3a5a2a', height: 55 },
    leaves: { color: '#3a7a3a', style: 'serrated', count: 3 },
    bloom: { color: '#d63a4a', centerColor: '#8a1a2a', kind: 'rose', size: 20, petals: 12 } },
  { id: 'tulip',     name: 'Tulip',     rarity: 'uncommon',
    stem: { color: '#4a8a3a', height: 70 },
    leaves: { color: '#5aa84a', style: 'blade', count: 2 },
    bloom: { color: '#e84a8a', centerColor: '#a02060', kind: 'cup', size: 18, petals: 6 } },
  { id: 'lavender',  name: 'Lavender',  rarity: 'uncommon',
    stem: { color: '#5a7a4a', height: 70 },
    leaves: { color: '#7a9a6a', style: 'blade', count: 3 },
    bloom: { color: '#a674d8', centerColor: '#6a4090', kind: 'spike', size: 22, petals: 8 } },
  { id: 'lily',      name: 'Lily',      rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#5a9a4a', style: 'blade', count: 3 },
    bloom: { color: '#f8e8e8', centerColor: '#d8a020', kind: 'trumpet', size: 22, petals: 6 } },
  { id: 'iris',      name: 'Iris',      rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#5a9a4a', style: 'blade', count: 2 },
    bloom: { color: '#6a5ad0', centerColor: '#f0c040', kind: 'iris', size: 22, petals: 6 } },
  { id: 'hydrangea', name: 'Hydrangea', rarity: 'uncommon',
    stem: { color: '#4a6a2a', height: 50 },
    leaves: { color: '#3a7a3a', style: 'oval', count: 3 },
    bloom: { color: '#7ab4e8', centerColor: '#a4d0f4', kind: 'cluster', size: 24, petals: 9 } },
  { id: 'marigold',  name: 'Marigold',  rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#5a8a3a', style: 'jagged', count: 3 },
    bloom: { color: '#f4843a', centerColor: '#a04020', kind: 'petals', size: 20, petals: 16 } },

  // ── RARE ───────────────────────────────────────────────────────────────
  { id: 'bonsai',          name: 'Bonsai',          rarity: 'rare',
    stem: { color: '#5a3a1a', height: 50, style: 'gnarled' },
    leaves: { color: '#3a7a3a', style: 'clump', count: 4 },
    bloom: null },
  { id: 'venus-flytrap',   name: 'Venus Flytrap',   rarity: 'rare',
    stem: { color: '#4a7a3a', height: 40 },
    leaves: { color: '#6ab46a', style: 'blade', count: 2 },
    bloom: { color: '#a0d878', centerColor: '#e84a4a', kind: 'jaws', size: 22, petals: 0 } },
  { id: 'monstera',        name: 'Monstera',        rarity: 'rare',
    stem: { color: '#3a5a2a', height: 45 },
    leaves: { color: '#2a8a3a', style: 'monstera', count: 3 },
    bloom: null },
  { id: 'bird-of-paradise',name: 'Bird of Paradise',rarity: 'rare',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#3a8a4a', style: 'paddle', count: 2 },
    bloom: { color: '#f4843a', centerColor: '#4a78d8', kind: 'paradise', size: 24, petals: 5 } },
  { id: 'peace-lily',      name: 'Peace Lily',      rarity: 'rare',
    stem: { color: '#3a5a2a', height: 60 },
    leaves: { color: '#2a6a3a', style: 'paddle', count: 3 },
    bloom: { color: '#f8f4ec', centerColor: '#e0d090', kind: 'spathe', size: 22, petals: 1 } },

  // ── LEGENDARY ──────────────────────────────────────────────────────────
  { id: 'cherry-blossom',  name: 'Cherry Blossom',  rarity: 'legendary',
    stem: { color: '#5a3a2a', height: 55, style: 'gnarled' },
    leaves: { color: '#7a4a3a', style: 'oval', count: 2 },
    bloom: { color: '#fcd6e0', centerColor: '#f0a8c4', kind: 'cluster', size: 30, petals: 14 } },
  { id: 'dragon-fruit',    name: 'Dragon Fruit',    rarity: 'legendary',
    stem: { color: '#3a5a2a', height: 40 },
    leaves: { color: '#4a8a3a', style: 'spike', count: 4 },
    bloom: { color: '#e8345a', centerColor: '#80c060', kind: 'dragon', size: 26, petals: 8 } },
  { id: 'ghost-orchid',    name: 'Ghost Orchid',    rarity: 'legendary',
    stem: { color: '#4a5a4a', height: 60 },
    leaves: null,
    bloom: { color: '#f4f8f4', centerColor: '#d0e0d8', kind: 'orchid', size: 26, petals: 5 } },

  // ── SECRET ─────────────────────────────────────────────────────────────
  { id: 'rainbow-rose',    name: 'Rainbow Rose',    rarity: 'secret',
    stem: { color: '#4a6a3a', height: 60 },
    leaves: { color: '#5a8a4a', style: 'serrated', count: 3 },
    bloom: { color: 'rainbow', centerColor: '#ffffff', kind: 'rose', size: 22, petals: 14 } },
  { id: 'midnight-bloom',  name: 'Midnight Bloom',  rarity: 'secret',
    stem: { color: '#2a1a3a', height: 60 },
    leaves: { color: '#3a2a4a', style: 'oval', count: 3 },
    bloom: { color: '#3a1a4a', centerColor: '#d050d8', kind: 'petals', size: 24, petals: 10 } },
];

const BY_ID = new Map(PLANTS.map(p => [p.id, p]));
export const plantById = (id) => BY_ID.get(id);
export const plantsByRarity = (rarity) => PLANTS.filter(p => p.rarity === rarity);
