export const RARITIES = ['common', 'uncommon', 'rare', 'legendary', 'secret'];

// Each plant defines: stem, leaves, bloom. All optional — set to null to skip.
// Colors are hex strings. Builder in svg.js renders these to a 100x120 viewBox.
export const PLANTS = [
  // ── COMMON ─────────────────────────────────────────────────────────────
  { id: 'grass',     name: 'Grass',     rarity: 'common',
    stem: null,
    leaves: { color: '#4ea84a', style: 'blade', count: 9 },
    bloom: null },
  { id: 'clover',    name: 'Clover',    rarity: 'common',
    stem: { color: '#3a8b3a', height: 30 },
    leaves: { color: '#5cb85c', style: 'trefoil', count: 1 },
    bloom: null },
  { id: 'dandelion', name: 'Dandelion', rarity: 'common',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#6cb05c', style: 'jagged', count: 4 },
    bloom: { color: '#ffd24a', centerColor: '#ffb022', kind: 'puff', size: 14, petals: 0 } },
  { id: 'moss',      name: 'Moss',      rarity: 'common',
    stem: null,
    leaves: { color: '#3a7a3a', style: 'clump', count: 7 },
    bloom: null },
  { id: 'fern',      name: 'Fern',      rarity: 'common',
    stem: { color: '#3a6a2a', height: 50 },
    leaves: { color: '#4a8a3a', style: 'frond', count: 5 },
    bloom: null },
  { id: 'daisy',     name: 'Daisy',     rarity: 'common',
    stem: { color: '#4a7a3a', height: 60 },
    leaves: { color: '#5ca84a', style: 'oval', count: 2 },
    bloom: { color: '#f4f0e6', centerColor: '#f0c040', kind: 'petals', size: 18, petals: 10 } },
  { id: 'buttercup', name: 'Buttercup', rarity: 'common',
    stem: { color: '#4a8a3a', height: 50 },
    leaves: { color: '#5cb85c', style: 'jagged', count: 3 },
    bloom: { color: '#ffd84a', centerColor: '#d49020', kind: 'petals', size: 14, petals: 5 } },
  { id: 'mint',      name: 'Mint',      rarity: 'common',
    stem: { color: '#5a8a4a', height: 60 },
    leaves: { color: '#6cc06c', style: 'serrated', count: 6 },
    bloom: { color: '#f0f0e0', centerColor: '#c0c0a0', kind: 'cluster', size: 10, petals: 5 } },
  { id: 'basil',     name: 'Basil',     rarity: 'common',
    stem: { color: '#3a6a2a', height: 50 },
    leaves: { color: '#3a8a3a', style: 'oval', count: 6 },
    bloom: null },
  { id: 'parsley',   name: 'Parsley',   rarity: 'common',
    stem: { color: '#3a7a2a', height: 35 },
    leaves: { color: '#4a9a3a', style: 'curly', count: 6 },
    bloom: null },
  { id: 'chives',    name: 'Chives',    rarity: 'common',
    stem: null,
    leaves: { color: '#5a9a5a', style: 'blade', count: 7 },
    bloom: { color: '#b86fd8', centerColor: '#8a4ab0', kind: 'puff', size: 10, petals: 0 } },
  { id: 'ivy',       name: 'Ivy',       rarity: 'common',
    stem: { color: '#3a5a2a', height: 70 },
    leaves: { color: '#3a7a3a', style: 'heart', count: 5 },
    bloom: null },

  // ── UNCOMMON ───────────────────────────────────────────────────────────
  { id: 'sunflower', name: 'Sunflower', rarity: 'uncommon',
    stem: { color: '#4a7a2a', height: 65 },
    leaves: { color: '#5a9a3a', style: 'heart', count: 2 },
    bloom: { color: '#ffd224', centerColor: '#6a3a18', kind: 'petals', size: 26, petals: 14 } },
  { id: 'rose',      name: 'Rose',      rarity: 'uncommon',
    stem: { color: '#3a5a2a', height: 55 },
    leaves: { color: '#3a7a3a', style: 'serrated', count: 3 },
    bloom: { color: '#d63a4a', centerColor: '#8a1a2a', kind: 'rose', size: 20, petals: 12 } },
  { id: 'tulip',     name: 'Tulip',     rarity: 'uncommon',
    stem: { color: '#4a8a3a', height: 70 },
    leaves: { color: '#5aa84a', style: 'blade', count: 2 },
    bloom: { color: '#e84a8a', centerColor: '#a02060', kind: 'cup', size: 18, petals: 6 } },
  { id: 'lavender',  name: 'Lavender',  rarity: 'uncommon',
    stem: { color: '#5a7a4a', height: 70 },
    leaves: { color: '#7a9a6a', style: 'blade', count: 3 },
    bloom: { color: '#a674d8', centerColor: '#6a4090', kind: 'spike', size: 22, petals: 8 } },
  { id: 'lily',      name: 'Lily',      rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#5a9a4a', style: 'blade', count: 3 },
    bloom: { color: '#f8e8e8', centerColor: '#d8a020', kind: 'trumpet', size: 22, petals: 6 } },
  { id: 'iris',      name: 'Iris',      rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#5a9a4a', style: 'blade', count: 2 },
    bloom: { color: '#6a5ad0', centerColor: '#f0c040', kind: 'iris', size: 22, petals: 6 } },
  { id: 'hydrangea', name: 'Hydrangea', rarity: 'uncommon',
    stem: { color: '#4a6a2a', height: 50 },
    leaves: { color: '#3a7a3a', style: 'oval', count: 3 },
    bloom: { color: '#7ab4e8', centerColor: '#a4d0f4', kind: 'cluster', size: 24, petals: 9 } },
  { id: 'marigold',  name: 'Marigold',  rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#5a8a3a', style: 'jagged', count: 3 },
    bloom: { color: '#f4843a', centerColor: '#a04020', kind: 'petals', size: 20, petals: 16 } },

  // ── RARE ───────────────────────────────────────────────────────────────
  { id: 'bonsai',          name: 'Bonsai',          rarity: 'rare',
    stem: { color: '#5a3a1a', height: 50, style: 'gnarled' },
    leaves: { color: '#3a7a3a', style: 'clump', count: 4 },
    bloom: null },
  { id: 'venus-flytrap',   name: 'Venus Flytrap',   rarity: 'rare',
    stem: { color: '#4a7a3a', height: 40 },
    leaves: { color: '#6ab46a', style: 'blade', count: 2 },
    bloom: { color: '#a0d878', centerColor: '#e84a4a', kind: 'jaws', size: 22, petals: 0 } },
  { id: 'monstera',        name: 'Monstera',        rarity: 'rare',
    stem: { color: '#3a5a2a', height: 45 },
    leaves: { color: '#2a8a3a', style: 'monstera', count: 3 },
    bloom: null },
  { id: 'bird-of-paradise',name: 'Bird of Paradise',rarity: 'rare',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#3a8a4a', style: 'paddle', count: 2 },
    bloom: { color: '#f4843a', centerColor: '#4a78d8', kind: 'paradise', size: 24, petals: 5 } },
  { id: 'peace-lily',      name: 'Peace Lily',      rarity: 'rare',
    stem: { color: '#3a5a2a', height: 60 },
    leaves: { color: '#2a6a3a', style: 'paddle', count: 3 },
    bloom: { color: '#f8f4ec', centerColor: '#e0d090', kind: 'spathe', size: 22, petals: 1 } },

  // ── LEGENDARY ──────────────────────────────────────────────────────────
  { id: 'cherry-blossom',  name: 'Cherry Blossom',  rarity: 'legendary',
    stem: { color: '#5a3a2a', height: 55, style: 'gnarled' },
    leaves: { color: '#7a4a3a', style: 'oval', count: 2 },
    bloom: { color: '#fcd6e0', centerColor: '#f0a8c4', kind: 'cluster', size: 30, petals: 14 } },
  { id: 'dragon-fruit',    name: 'Dragon Fruit',    rarity: 'legendary',
    stem: { color: '#3a5a2a', height: 40 },
    leaves: { color: '#4a8a3a', style: 'spike', count: 4 },
    bloom: { color: '#e8345a', centerColor: '#80c060', kind: 'dragon', size: 26, petals: 8 } },
  { id: 'ghost-orchid',    name: 'Ghost Orchid',    rarity: 'legendary',
    stem: { color: '#4a5a4a', height: 60 },
    leaves: null,
    bloom: { color: '#f4f8f4', centerColor: '#d0e0d8', kind: 'orchid', size: 26, petals: 5 } },

  // ── SECRET ─────────────────────────────────────────────────────────────
  { id: 'rainbow-rose',    name: 'Rainbow Rose',    rarity: 'secret',
    stem: { color: '#4a6a3a', height: 60 },
    leaves: { color: '#5a8a4a', style: 'serrated', count: 3 },
    bloom: { color: 'rainbow', centerColor: '#ffffff', kind: 'rose', size: 22, petals: 14 } },
  { id: 'midnight-bloom',  name: 'Midnight Bloom',  rarity: 'secret',
    stem: { color: '#2a1a3a', height: 60 },
    leaves: { color: '#3a2a4a', style: 'oval', count: 3 },
    bloom: { color: '#3a1a4a', centerColor: '#d050d8', kind: 'petals', size: 24, petals: 10 } },

  // ── COMMON (extra) ─────────────────────────────────────────────────────
  { id: 'wheat',     name: 'Wheat',     rarity: 'common',
    stem: { color: '#b89a3a', height: 70 },
    leaves: { color: '#c8b04a', style: 'blade', count: 4 },
    bloom: { color: '#e8c45a', centerColor: '#8a6420', kind: 'spike', size: 18, petals: 0 } },
  { id: 'crabgrass', name: 'Crabgrass', rarity: 'common',
    stem: null,
    leaves: { color: '#6aa84a', style: 'blade', count: 10 },
    bloom: null },
  { id: 'thistle',   name: 'Thistle',   rarity: 'common',
    stem: { color: '#5a7a3a', height: 60 },
    leaves: { color: '#7a9a4a', style: 'jagged', count: 4 },
    bloom: { color: '#a674d8', centerColor: '#5a4080', kind: 'puff', size: 12, petals: 0 } },
  { id: 'nettle',    name: 'Nettle',    rarity: 'common',
    stem: { color: '#4a6a2a', height: 55 },
    leaves: { color: '#5a8a3a', style: 'serrated', count: 4 },
    bloom: null },
  { id: 'cornflower',name: 'Cornflower',rarity: 'common',
    stem: { color: '#5a7a4a', height: 65 },
    leaves: { color: '#7a9a6a', style: 'blade', count: 3 },
    bloom: { color: '#4a78d8', centerColor: '#2a4090', kind: 'petals', size: 16, petals: 8 } },
  { id: 'chamomile', name: 'Chamomile', rarity: 'common',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#6ca84a', style: 'jagged', count: 3 },
    bloom: { color: '#f8f4e8', centerColor: '#f0c040', kind: 'petals', size: 14, petals: 10 } },
  { id: 'yarrow',    name: 'Yarrow',    rarity: 'common',
    stem: { color: '#5a7a4a', height: 60 },
    leaves: { color: '#7a9a5a', style: 'serrated', count: 3 },
    bloom: { color: '#f4f0e0', centerColor: '#c0b080', kind: 'cluster', size: 16, petals: 11 } },
  { id: 'sage',      name: 'Sage',      rarity: 'common',
    stem: { color: '#6a7a5a', height: 55 },
    leaves: { color: '#8aa48a', style: 'oval', count: 5 },
    bloom: { color: '#8a74c8', centerColor: '#5a4080', kind: 'spike', size: 18, petals: 6 } },
  { id: 'rosemary',  name: 'Rosemary',  rarity: 'common',
    stem: { color: '#5a6a4a', height: 60 },
    leaves: { color: '#6a8a6a', style: 'blade', count: 8 },
    bloom: { color: '#9a9ad8', centerColor: '#6060a0', kind: 'cluster', size: 10, petals: 5 } },
  { id: 'oregano',   name: 'Oregano',   rarity: 'common',
    stem: { color: '#4a6a3a', height: 45 },
    leaves: { color: '#5a8a4a', style: 'oval', count: 5 },
    bloom: { color: '#e8a4c4', centerColor: '#a06080', kind: 'cluster', size: 12, petals: 6 } },
  { id: 'thyme',     name: 'Thyme',     rarity: 'common',
    stem: null,
    leaves: { color: '#5a7a4a', style: 'clump', count: 8 },
    bloom: { color: '#c894d8', centerColor: '#7a5090', kind: 'cluster', size: 10, petals: 4 } },
  { id: 'cilantro',  name: 'Cilantro',  rarity: 'common',
    stem: { color: '#3a7a2a', height: 40 },
    leaves: { color: '#5aaa3a', style: 'curly', count: 5 },
    bloom: null },
  { id: 'dill',      name: 'Dill',      rarity: 'common',
    stem: { color: '#4a7a2a', height: 60 },
    leaves: { color: '#7ab44a', style: 'frond', count: 5 },
    bloom: { color: '#e8d440', centerColor: '#a08020', kind: 'cluster', size: 14, petals: 8 } },
  { id: 'cattail',   name: 'Cattail',   rarity: 'common',
    stem: { color: '#5a7a3a', height: 75 },
    leaves: { color: '#6a9a4a', style: 'blade', count: 4 },
    bloom: { color: '#5a3a1a', centerColor: '#3a200c', kind: 'spike', size: 22, petals: 0 } },
  { id: 'plantain',  name: 'Plantain',  rarity: 'common',
    stem: { color: '#4a6a2a', height: 60 },
    leaves: { color: '#5a8a3a', style: 'oval', count: 4 },
    bloom: { color: '#7a9a4a', centerColor: '#4a6a20', kind: 'spike', size: 18, petals: 0 } },
  { id: 'shamrock',  name: 'Shamrock',  rarity: 'common',
    stem: { color: '#3a7a2a', height: 28 },
    leaves: { color: '#4ab84a', style: 'trefoil', count: 1 },
    bloom: null },
  { id: 'babys-breath', name: "Baby's Breath", rarity: 'common',
    stem: { color: '#5a7a4a', height: 65 },
    leaves: { color: '#6a9a5a', style: 'blade', count: 3 },
    bloom: { color: '#f8f4f0', centerColor: '#d8d4c8', kind: 'cluster', size: 14, petals: 14 } },
  { id: 'aster',     name: 'Aster',     rarity: 'common',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#5a9a4a', style: 'oval', count: 3 },
    bloom: { color: '#a474d8', centerColor: '#f0c040', kind: 'petals', size: 14, petals: 12 } },

  // ── UNCOMMON (extra) ───────────────────────────────────────────────────
  { id: 'carnation', name: 'Carnation', rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 60 },
    leaves: { color: '#6a9a5a', style: 'blade', count: 2 },
    bloom: { color: '#e84a78', centerColor: '#a02050', kind: 'rose', size: 18, petals: 14 } },
  { id: 'peony',     name: 'Peony',     rarity: 'uncommon',
    stem: { color: '#3a6a2a', height: 55 },
    leaves: { color: '#3a8a3a', style: 'serrated', count: 3 },
    bloom: { color: '#f4a4c4', centerColor: '#d06090', kind: 'cluster', size: 24, petals: 14 } },
  { id: 'snapdragon',name: 'Snapdragon',rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 70 },
    leaves: { color: '#5a9a4a', style: 'blade', count: 3 },
    bloom: { color: '#f47a4a', centerColor: '#a04020', kind: 'spike', size: 22, petals: 6 } },
  { id: 'zinnia',    name: 'Zinnia',    rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 60 },
    leaves: { color: '#5a9a4a', style: 'oval', count: 3 },
    bloom: { color: '#f44a6a', centerColor: '#f0c040', kind: 'petals', size: 20, petals: 12 } },
  { id: 'azalea',    name: 'Azalea',    rarity: 'uncommon',
    stem: { color: '#5a3a2a', height: 45, style: 'gnarled' },
    leaves: { color: '#3a7a3a', style: 'oval', count: 4 },
    bloom: { color: '#e864a4', centerColor: '#a03070', kind: 'cluster', size: 22, petals: 10 } },
  { id: 'poppy',     name: 'Poppy',     rarity: 'uncommon',
    stem: { color: '#5a7a4a', height: 70 },
    leaves: { color: '#7a9a5a', style: 'jagged', count: 3 },
    bloom: { color: '#e83a3a', centerColor: '#2a1a1a', kind: 'petals', size: 22, petals: 6 } },
  { id: 'dahlia',    name: 'Dahlia',    rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 55 },
    leaves: { color: '#5a8a4a', style: 'serrated', count: 3 },
    bloom: { color: '#d84a8a', centerColor: '#6a2050', kind: 'petals', size: 22, petals: 16 } },
  { id: 'gerbera',   name: 'Gerbera',   rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#6aa44a', style: 'jagged', count: 3 },
    bloom: { color: '#f48a3a', centerColor: '#4a3010', kind: 'petals', size: 22, petals: 18 } },
  { id: 'chrysanthemum', name: 'Chrysanthemum', rarity: 'uncommon',
    stem: { color: '#4a6a3a', height: 55 },
    leaves: { color: '#5a8a4a', style: 'jagged', count: 3 },
    bloom: { color: '#f4c040', centerColor: '#a07020', kind: 'cluster', size: 22, petals: 16 } },
  { id: 'forget-me-not', name: 'Forget-Me-Not', rarity: 'uncommon',
    stem: { color: '#5a7a4a', height: 50 },
    leaves: { color: '#6a9a5a', style: 'oval', count: 3 },
    bloom: { color: '#6aa4e8', centerColor: '#f4d860', kind: 'cluster', size: 16, petals: 8 } },
  { id: 'bluebell',  name: 'Bluebell',  rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 65 },
    leaves: { color: '#5a9a4a', style: 'blade', count: 2 },
    bloom: { color: '#5a78d8', centerColor: '#2a4090', kind: 'cup', size: 16, petals: 6 } },
  { id: 'crocus',    name: 'Crocus',    rarity: 'uncommon',
    stem: { color: '#5a8a4a', height: 45 },
    leaves: { color: '#6aa44a', style: 'blade', count: 3 },
    bloom: { color: '#9a64d8', centerColor: '#f0a020', kind: 'cup', size: 18, petals: 6 } },
  { id: 'hibiscus',  name: 'Hibiscus',  rarity: 'uncommon',
    stem: { color: '#3a6a2a', height: 55 },
    leaves: { color: '#3a8a3a', style: 'heart', count: 3 },
    bloom: { color: '#f04a6a', centerColor: '#f4d040', kind: 'trumpet', size: 24, petals: 5 } },
  { id: 'morning-glory', name: 'Morning Glory', rarity: 'uncommon',
    stem: { color: '#4a7a3a', height: 75 },
    leaves: { color: '#5a9a4a', style: 'heart', count: 4 },
    bloom: { color: '#8a64d8', centerColor: '#f4f0e0', kind: 'trumpet', size: 22, petals: 5 } },
  { id: 'wisteria',  name: 'Wisteria',  rarity: 'uncommon',
    stem: { color: '#5a3a1a', height: 50, style: 'gnarled' },
    leaves: { color: '#5a8a4a', style: 'oval', count: 3 },
    bloom: { color: '#a484d8', centerColor: '#6a4090', kind: 'spike', size: 26, petals: 10 } },

  // ── RARE (extra) ───────────────────────────────────────────────────────
  { id: 'cactus',    name: 'Cactus',    rarity: 'rare',
    stem: null,
    leaves: { color: '#4a8a4a', style: 'spike', count: 3 },
    bloom: { color: '#f4a4c4', centerColor: '#f4d040', kind: 'petals', size: 16, petals: 7 } },
  { id: 'aloe',      name: 'Aloe',      rarity: 'rare',
    stem: null,
    leaves: { color: '#7ab47a', style: 'spike', count: 4 },
    bloom: { color: '#f08040', centerColor: '#a04020', kind: 'spike', size: 20, petals: 6 } },
  { id: 'anthurium', name: 'Anthurium', rarity: 'rare',
    stem: { color: '#3a6a2a', height: 50 },
    leaves: { color: '#2a7a3a', style: 'heart', count: 3 },
    bloom: { color: '#e83a3a', centerColor: '#f4e840', kind: 'spathe', size: 22, petals: 1 } },
  { id: 'fiddle-leaf-fig', name: 'Fiddle Leaf Fig', rarity: 'rare',
    stem: { color: '#5a4a2a', height: 60, style: 'gnarled' },
    leaves: { color: '#2a7a3a', style: 'paddle', count: 4 },
    bloom: null },
  { id: 'snake-plant', name: 'Snake Plant', rarity: 'rare',
    stem: null,
    leaves: { color: '#3a7a4a', style: 'blade', count: 6 },
    bloom: null },
  { id: 'philodendron', name: 'Philodendron', rarity: 'rare',
    stem: { color: '#3a5a2a', height: 50 },
    leaves: { color: '#2a8a3a', style: 'heart', count: 4 },
    bloom: null },
  { id: 'lotus',     name: 'Lotus',     rarity: 'rare',
    stem: { color: '#5a7a4a', height: 55 },
    leaves: { color: '#6aa44a', style: 'paddle', count: 2 },
    bloom: { color: '#f8c4d8', centerColor: '#f4d040', kind: 'petals', size: 24, petals: 10 } },
  { id: 'protea',    name: 'Protea',    rarity: 'rare',
    stem: { color: '#5a6a4a', height: 60 },
    leaves: { color: '#7a9a6a', style: 'oval', count: 3 },
    bloom: { color: '#f4a08a', centerColor: '#a04050', kind: 'cluster', size: 26, petals: 14 } },
  { id: 'pitcher-plant', name: 'Pitcher Plant', rarity: 'rare',
    stem: { color: '#4a6a3a', height: 45 },
    leaves: { color: '#5a8a4a', style: 'blade', count: 2 },
    bloom: { color: '#a4c44a', centerColor: '#7a3030', kind: 'cup', size: 22, petals: 5 } },
  { id: 'jade-plant',name: 'Jade Plant',rarity: 'rare',
    stem: { color: '#5a4a2a', height: 40, style: 'gnarled' },
    leaves: { color: '#6ab46a', style: 'oval', count: 6 },
    bloom: null },

  // ── LEGENDARY (extra) ──────────────────────────────────────────────────
  { id: 'blue-rose', name: 'Blue Rose', rarity: 'legendary',
    stem: { color: '#3a5a4a', height: 60 },
    leaves: { color: '#4a7a6a', style: 'serrated', count: 3 },
    bloom: { color: '#4a74d8', centerColor: '#a4c4f4', kind: 'rose', size: 22, petals: 14 } },
  { id: 'corpse-flower', name: 'Corpse Flower', rarity: 'legendary',
    stem: { color: '#5a3a3a', height: 55 },
    leaves: { color: '#3a5a3a', style: 'monstera', count: 2 },
    bloom: { color: '#8a3050', centerColor: '#f4e8c4', kind: 'spathe', size: 28, petals: 1 } },
  { id: 'moonflower',name: 'Moonflower',rarity: 'legendary',
    stem: { color: '#4a5a5a', height: 65 },
    leaves: { color: '#5a7a7a', style: 'heart', count: 3 },
    bloom: { color: '#f4f4f8', centerColor: '#c0d0e8', kind: 'trumpet', size: 26, petals: 6 } },
  { id: 'firebloom', name: 'Firebloom', rarity: 'legendary',
    stem: { color: '#6a3a1a', height: 60, style: 'gnarled' },
    leaves: { color: '#a04020', style: 'jagged', count: 3 },
    bloom: { color: '#f44a1a', centerColor: '#f4e040', kind: 'petals', size: 26, petals: 12 } },
  { id: 'queen-of-the-night', name: 'Queen of the Night', rarity: 'legendary',
    stem: { color: '#3a5a3a', height: 50 },
    leaves: { color: '#4a7a4a', style: 'spike', count: 3 },
    bloom: { color: '#f8f0e0', centerColor: '#f4c860', kind: 'orchid', size: 26, petals: 5 } },

  // ── SECRET (extra) ─────────────────────────────────────────────────────
  { id: 'galaxy-petal', name: 'Galaxy Petal', rarity: 'secret',
    stem: { color: '#3a2a5a', height: 60 },
    leaves: { color: '#5a4a8a', style: 'serrated', count: 3 },
    bloom: { color: 'rainbow', centerColor: '#f4f0ff', kind: 'iris', size: 24, petals: 6 } },
  { id: 'void-lotus', name: 'Void Lotus', rarity: 'secret',
    stem: { color: '#1a1a2a', height: 50 },
    leaves: { color: '#2a2a4a', style: 'paddle', count: 2 },
    bloom: { color: '#1a0a2a', centerColor: '#a040f4', kind: 'petals', size: 26, petals: 10 } },
];

const BY_ID = new Map(PLANTS.map(p => [p.id, p]));
export const plantById = (id) => BY_ID.get(id);
export const plantsByRarity = (rarity) => PLANTS.filter(p => p.rarity === rarity);
